description: 'A question-answering chatbot that provides answers to user queries'
dataset_path: 'C:/Users/m.gheysari/Desktop/QA-All.xlsx'
mongodb_user: 'qa'
mongodb_pass: 'Aa1234'
mongodb_ip: '10.187.105.206'
mongo_port: '27017'
mongodb_db: 'qa'
mongodb_coll: 'qa'
mongodb_category_coll: 'category'
elastic_host: '10.187.160.104'
elastic_port: '5011'
elastic_index_name: 'ai-app-logs-stage'