# Generated by Django 3.2.9 on 2024-02-10 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backoffice',
            fields=[
                ('updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_res', models.JSONField(null=True)),
                ('process_type', models.IntegerField(choices=[(0, 'AUTH'), (1, 'OCR')], default=None)),
                ('process_errors', models.JSONField(default=None, null=True)),
                ('process_status', models.IntegerField(choices=[(0, 'INIT'), (1, 'Pending'), (2, 'Complete'), (3, 'Failed'), (4, 'Error')], default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process', to='process.process')),
            ],
        ),
    ]
