# Generated by Django 3.2.9 on 2024-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_updated', models.DateTimeField(auto_created=True, auto_now=True)),
                ('process_pk', models.AutoField(primary_key=True, serialize=False)),
                ('process_id', models.CharField(max_length=255)),
                ('process_try', models.IntegerField(default=0)),
                ('process_url', models.JSONField(null=True)),
                ('process_type', models.IntegerField(choices=[(0, 'AUTH'), (1, 'OCR')])),
                ('process_errors', models.JSONField(null=True)),
                ('process_status', models.IntegerField(choices=[(0, 'INIT'), (1, 'Pending'), (2, 'Complete'), (3, 'Failed'), (4, 'Error')])),
                ('process_created', models.DateTimeField(auto_now_add=True)),
                ('process_json', models.JSONField()),
            ],
            options={
                'ordering': ['-process_created'],
            },
        ),
    ]
